'use strict';
const GAME_ID='kingdomino';
const GAME_NAME='KINGDOMINO';
const APP_VERSION='v0.1.0';
const WORKER_ORIGIN='https://kingdomino-online.naitoryo7110.workers.dev';
const COMMON_PLAYER_NAME_KEY='boardgamePlayerName';
const ROOM_IDS=['room1','room2','room3','room4'];
const NAME_DRAFT_KEY='kingdomino-name-draft';
const ACTIVE_ROOM_KEY=`${GAME_ID}-online-room`;
const ACTIVE_NAME_KEY=`${GAME_ID}-online-active-name`;
const TERRAINS={wheat:'小麦畑',forest:'森',water:'湖',grass:'草原',swamp:'沼地',mine:'鉱山'};
const TERRAIN_EMOJI={wheat:'🌾',forest:'🌲',water:'🌊',grass:'🌿',swamp:'🟫',mine:'⛰️'};
let state=null,ws=null,currentRoomId=null,currentPlayerName='',token='',actionSeq=0,reconnectTimer=null,commonNameSavedForSession=null;
let selectedDir=0,selectedAnchor=null,viewPlayerId=null;
const app=document.getElementById('app');
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function commonSavedName(){return String(localStorage.getItem(COMMON_PLAYER_NAME_KEY)||'').trim().slice(0,32)}
function saveCommonNameOnActualStart(name){name=String(name||'').trim().slice(0,32);if(name)localStorage.setItem(COMMON_PLAYER_NAME_KEY,name)}
function tokenKey(r){return `${GAME_ID}-online-token-${r}`}
function getToken(r){let t=localStorage.getItem(tokenKey(r));if(!t){t=crypto.randomUUID().replace(/-/g,'');localStorage.setItem(tokenKey(r),t)}return t}
function newActionId(p='op'){actionSeq=(actionSeq+1)%1e6;return [p,Date.now(),actionSeq,Math.random().toString(36).slice(2,8)].join('-')}
function roomStatusLabel(r){if(r.status==='playing')return'ゲーム中';if(r.status==='finished')return'終了';return'待機中'}
async function jfetch(url,opt){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'通信に失敗しました。');return d}
async function loadRooms(){const settled=await Promise.allSettled(ROOM_IDS.map(r=>jfetch(`${WORKER_ORIGIN}/room-summary?roomId=${r}&_=${Date.now()}`,{cache:'no-store'})));renderTitle(settled)}
function renderTitle(results){const draft=sessionStorage.getItem(NAME_DRAFT_KEY)??commonSavedName()??'';app.innerHTML=`<div class='wrap'><div class='top'><div class='title'>KINGDOMINO ONLINE</div><div class='ver'>${APP_VERSION}</div></div><div class='panel namebox'><div>プレイヤー名</div><input id='nameInput' maxlength='32' value='${esc(draft)}'><div class='actions'><button class='btn secondary' id='refreshRooms'>ROOM更新</button></div><div id='titleErr' class='error'></div></div><div class='room-grid'>${ROOM_IDS.map((rid,i)=>{const x=results?.[i];if(!x||x.status==='rejected')return `<article class='panel room-card'><div class='room-head'><b>ROOM ${i+1}</b><span class='error'>取得失敗</span></div><div class='muted'>ROOM情報を取得できません。</div><button data-room='${rid}'>参加する</button><button class='reset' data-reset='${rid}'>初期化</button></article>`;const r=x.value.room||x.value;const names=(r.players||[]).map(p=>p.name).join('、')||'なし';return `<article class='panel room-card'><div class='room-head'><b>ROOM ${i+1}</b><span>${roomStatusLabel(r)}</span></div><div>${r.count||0} / 4人</div><div class='muted'>参加者：${esc(names)}</div><button data-room='${rid}'>${r.reconnect?'再接続':'参加する'}</button><button class='reset' data-reset='${rid}'>初期化</button></article>`}).join('')}</div></div>`;
const ni=document.getElementById('nameInput');ni.addEventListener('input',e=>sessionStorage.setItem(NAME_DRAFT_KEY,e.target.value));document.getElementById('refreshRooms').onclick=loadRooms;app.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>joinRoom(b.dataset.room));app.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>resetRoom(b.dataset.reset));}
async function resetRoom(rid){if(!confirm(`ROOM ${ROOM_IDS.indexOf(rid)+1} を初期化しますか？`))return;try{await jfetch(`${WORKER_ORIGIN}/reset-empty?roomId=${encodeURIComponent(rid)}`,{method:'POST',cache:'no-store'});await loadRooms()}catch(e){alert(e.message)}}
async function joinRoom(rid){const name=String(document.getElementById('nameInput')?.value||'').trim().slice(0,32);if(!name){document.getElementById('titleErr').textContent='プレイヤー名を入力してください。';return}const t=getToken(rid);try{await jfetch(`${WORKER_ORIGIN}/join-check?roomId=${encodeURIComponent(rid)}&name=${encodeURIComponent(name)}&token=${encodeURIComponent(t)}`,{cache:'no-store'});currentRoomId=rid;currentPlayerName=name;token=t;localStorage.setItem(ACTIVE_ROOM_KEY,rid);localStorage.setItem(ACTIVE_NAME_KEY,name);connectWs()}catch(e){document.getElementById('titleErr').textContent=e.message}}
function wsUrl(){return WORKER_ORIGIN.replace(/^http/,'ws')+`/ws?roomId=${encodeURIComponent(currentRoomId)}&name=${encodeURIComponent(currentPlayerName)}&token=${encodeURIComponent(token)}`}
function connectWs(){clearTimeout(reconnectTimer);try{ws=new WebSocket(wsUrl());ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='state'){state=m.state;onState() }else if(m.type==='error'){alert(m.error)}};ws.onclose=()=>{if(currentRoomId)scheduleReconnect()};ws.onerror=()=>ws.close()}catch{scheduleReconnect()}}
function scheduleReconnect(){clearTimeout(reconnectTimer);reconnectTimer=setTimeout(()=>{if(currentRoomId)connectWs()},1300)}
function send(type,payload={}){if(ws?.readyState!==WebSocket.OPEN)return;ws.send(JSON.stringify({type,actionId:newActionId(type),...payload}))}
function me(){return state?.players?.find(p=>p.token===token)}
function isHost(){return me()?.id===state?.hostId}
function onState(){const m=me();if(state&&(state.status==='playing'||state.gameStarted)&&state.gameSessionId&&commonNameSavedForSession!==state.gameSessionId){saveCommonNameOnActualStart(currentPlayerName);commonNameSavedForSession=state.gameSessionId}if(!viewPlayerId&&m)viewPlayerId=m.id;if(state.status==='lobby')renderLobby();else renderGame();maybeRunCpu()}
function renderLobby(){const m=me();const host=isHost();app.innerHTML=`<div class='wrap'><div class='top'><div class='title'>KINGDOMINO ONLINE</div><div class='ver'>${APP_VERSION}</div></div><div class='lobby-grid'><section class='panel'><h2>ROOM ${ROOM_IDS.indexOf(currentRoomId)+1}</h2><div class='players'>${(state.players||[]).map(p=>`<div class='player-row'><span>${esc(p.name)}${p.id===state.hostId?' 👑':''}</span><span>${p.cpu?'CPU':'PLAYER'}</span></div>`).join('')}</div>${host?`<div class='actions'><button class='btn secondary' id='addCpu'>CPU追加</button><button class='btn secondary' id='removeCpu'>CPU削除</button></div>`:''}</section><section class='panel settings'><h3>ゲーム設定</h3><label>CPU難易度 <select id='cpuLevel' ${host?'':'disabled'}><option value='easy'>かんたん</option><option value='normal'>ふつう</option><option value='hard'>つよい</option></select></label><label>ハーモニー +5 <input id='harmony' type='checkbox' ${state.settings?.harmony?'checked':''} ${host?'':'disabled'}></label><label>ミドルキングダム +10 <input id='middle' type='checkbox' ${state.settings?.middle?'checked':''} ${host?'':'disabled'}></label><label>2人戦 7×7 <input id='mighty' type='checkbox' ${state.settings?.mighty?'checked':''} ${host?'':'disabled'}></label>${host?`<div class='actions'><button class='btn good' id='startGame'>ゲーム開始</button></div>`:''}<div class='actions'><button class='btn danger' id='leave'>退出</button></div><div class='muted'>2～4人で開始できます。2人通常戦は24枚、7×7は48枚を使用します。</div></section></div></div>`;
document.getElementById('cpuLevel').value=state.settings?.cpuLevel||'normal';if(host){document.getElementById('addCpu').onclick=()=>send('addCpu');document.getElementById('removeCpu').onclick=()=>send('removeCpu');['cpuLevel','harmony','middle','mighty'].forEach(id=>document.getElementById(id).onchange=()=>send('settings',{settings:{cpuLevel:document.getElementById('cpuLevel').value,harmony:document.getElementById('harmony').checked,middle:document.getElementById('middle').checked,mighty:document.getElementById('mighty').checked}}));document.getElementById('startGame').onclick=()=>send('start')}document.getElementById('leave').onclick=leaveRoom}
function leaveRoom(){send('leave');currentRoomId=null;state=null;viewPlayerId=null;localStorage.removeItem(ACTIVE_ROOM_KEY);localStorage.removeItem(ACTIVE_NAME_KEY);try{ws?.close()}catch{}loadRooms()}
function terrainCell(c,extra=''){if(!c)return `<div class='cell empty ${extra}'></div>`;if(c.terrain==='castle')return `<div class='cell castle ${extra}'>🏰</div>`;return `<div class='cell ${c.terrain} ${extra}' title='${TERRAINS[c.terrain]}'><span>${TERRAIN_EMOJI[c.terrain]}</span>${c.crowns?`<span class='crowns'>${'👑'.repeat(c.crowns)}</span>`:''}</div>`}
function boardBounds(board,size){const pts=Object.keys(board||{}).map(k=>k.split(',').map(Number));if(!pts.length)return {minX:-2,maxX:2,minY:-2,maxY:2};let xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]);let minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const pad=Math.max(0,size-(maxX-minX+1));minX-=Math.floor(pad/2);maxX=minX+size-1;const pady=Math.max(0,size-(maxY-minY+1));minY-=Math.floor(pady/2);maxY=minY+size-1;return{minX,maxX,minY,maxY}}
function renderBoard(p){const size=state.boardSize||5,displaySize=size+2,b=boardBounds(p.board,displaySize);let html=`<div class='board' style='grid-template-columns:repeat(${displaySize},1fr)'>`;for(let y=b.minY;y<=b.maxY;y++)for(let x=b.minX;x<=b.maxX;x++){const c=p.board?.[`${x},${y}`];const canPick=canAct()&&state.turnAction==='place'&&p.id===me()?.id&&!c;html+=terrainCell(c,canPick?'valid':'').replace('></div>',` data-x='${x}' data-y='${y}'></div>`)}return html+'</div>'}
function tileHtml(t,rowType){const claimed=t.claimedBy;const owner=claimed?state.tokens?.find(k=>k.id===claimed):null;const pl=owner?state.players.find(p=>p.id===owner.playerId):null;const initialClickable=rowType==='current'&&state.phase==='claim_initial'&&canAct()&&!claimed;const clickable=(rowType==='next'&&canAct()&&state.turnAction==='claim'&&!claimed)||initialClickable;const attr=initialClickable?`data-claim-initial='${t.tile.no}'`:(clickable?`data-claim='${t.tile.no}'`:'');return `<div class='domino ${claimed?'claimed':''} ${clickable?'claimable':''}' ${attr}><span class='num'>#${t.tile.no}</span><div class='half ${t.tile.a.terrain}'>${TERRAIN_EMOJI[t.tile.a.terrain]}${t.tile.a.crowns?`<span class='crowns'>${'👑'.repeat(t.tile.a.crowns)}</span>`:''}</div><div class='half ${t.tile.b.terrain}'>${TERRAIN_EMOJI[t.tile.b.terrain]}${t.tile.b.crowns?`<span class='crowns'>${'👑'.repeat(t.tile.b.crowns)}</span>`:''}</div><div class='claimtag'>${pl?esc(pl.name):'未選択'}</div></div>`}
function canAct(){const m=me();if(!m)return false;const tok=state.tokens?.find(t=>t.id===state.activeTokenId);return !!tok&&tok.playerId===m.id&&!m.cpu}
function activePlayer(){const t=state.tokens?.find(x=>x.id===state.activeTokenId);return t?state.players.find(p=>p.id===t.playerId):null}
function statusText(){if(state.status==='finished')return'ゲーム終了';if(state.phase==='claim_initial'){return `${activePlayer()?.name||''}：最初のタイルを選択`}if(state.turnAction==='place')return `${activePlayer()?.name||''}：タイルを配置`;if(state.turnAction==='claim')return `${activePlayer()?.name||''}：次のタイルを選択`;return'進行中'}
function renderGame(){const m=me();const vp=state.players.find(p=>p.id===viewPlayerId)||m||state.players[0];app.innerHTML=`<div class='game-layout'><aside class='panel side'><div class='top'><div class='title'>KINGDOMINO</div><div class='ver'>${APP_VERSION}</div></div>${state.players.map(p=>`<div class='player-card ${p.id===activePlayer()?.id?'active':''} ${p.id===m?.id?'me':''}' data-view='${p.id}'><b>${esc(p.name)}</b><div>${p.cpu?'CPU・':''}${p.score??0}点</div></div>`).join('')}<button class='btn danger' id='leave'>退出</button></aside><main class='panel center'><div class='status'>${esc(statusText())}　ラウンド ${state.round||1}</div><div class='muted'>表示：${esc(vp.name)}　${state.boardSize}×${state.boardSize}</div><div class='board-wrap'>${renderBoard(vp)}</div><div class='actions'>${canAct()&&state.turnAction==='place'?`<button class='btn secondary' id='rot'>↻ 回転</button>${state.canDiscard?`<button class='btn danger' id='discard'>配置不能・破棄</button>`:''}`:''}</div></main><aside class='panel tiles'><div class='rows'><div><b>現在のタイル</b><div class='tile-row'>${(state.currentRow||[]).map(t=>tileHtml(t,'current')).join('')}</div></div><div><b>次のタイル</b><div class='tile-row'>${(state.nextRow||[]).map(t=>tileHtml(t,'next')).join('')}</div></div></div></aside></div>${state.status==='finished'?resultOverlay():''}`;
app.querySelectorAll('[data-view]').forEach(e=>e.onclick=()=>{viewPlayerId=e.dataset.view;renderGame()});document.getElementById('leave').onclick=leaveRoom;if(document.getElementById('rot'))document.getElementById('rot').onclick=()=>{selectedDir=(selectedDir+1)%4;selectedAnchor=null};if(document.getElementById('discard'))document.getElementById('discard').onclick=()=>send('discard');app.querySelectorAll('.cell.valid').forEach(e=>e.onclick=()=>placeAt(+e.dataset.x,+e.dataset.y));app.querySelectorAll('[data-claim]').forEach(e=>e.onclick=()=>send('claim',{tileNo:+e.dataset.claim}));app.querySelectorAll('[data-claim-initial]').forEach(e=>e.onclick=()=>send('claimInitial',{tileNo:+e.dataset.claimInitial}));if(document.getElementById('closeResult'))document.getElementById('closeResult').onclick=()=>document.querySelector('.overlay')?.classList.add('hidden');if(document.getElementById('backLobby'))document.getElementById('backLobby').onclick=()=>send('backLobby');}
function placeAt(x,y){const dirs=[[1,0],[0,1],[-1,0],[0,-1]],d=dirs[selectedDir];send('place',{x,y,dx:d[0],dy:d[1]})}
function resultOverlay(){const sorted=[...state.players].sort((a,b)=>(b.score||0)-(a.score||0));return `<div class='overlay'><div class='panel result'><h2>リザルト</h2><table class='score-table'><tr><th>順位</th><th>名前</th><th>得点</th></tr>${sorted.map((p,i)=>`<tr><td>${i+1}</td><td>${esc(p.name)}</td><td>${p.score||0}点</td></tr>`).join('')}</table><div class='actions'>${isHost()?`<button class='btn good' id='backLobby'>ロビーへ戻る</button>`:''}<button class='btn secondary' id='closeResult'>盤面を見る</button></div></div></div>`}
function cpuTileScore(tile,p){const terr=[tile.a,tile.b];let s=terr.reduce((n,h)=>n+h.crowns*12,0)-tile.no*0.08;for(const h of terr){let count=0;Object.values(p.board||{}).forEach(c=>{if(c.terrain===h.terrain)count++});s+=count*1.2}return s}
function findCpuPlacement(tile,p,level='normal'){const dirs=[[1,0],[0,1],[-1,0],[0,-1]],cand=[];for(let y=-7;y<=7;y++)for(let x=-7;x<=7;x++)for(const [dx,dy] of dirs){if(clientLegal(tile,p.board,x,y,dx,dy,state.boardSize)){const before=p.score||0;const board=JSON.parse(JSON.stringify(p.board));board[`${x},${y}`]={terrain:tile.a.terrain,crowns:tile.a.crowns};board[`${x+dx},${y+dy}`]={terrain:tile.b.terrain,crowns:tile.b.crowns};let score=estimateScore(board);cand.push({x,y,dx,dy,v:score-before+(level==='hard'?(tile.a.crowns+tile.b.crowns)*2:0)})}}if(level==='easy')return cand[Math.floor(Math.random()*cand.length)]||null;cand.sort((a,b)=>b.v-a.v);return cand[0]||null}
function clientLegal(tile,board,x,y,dx,dy,size){const x2=x+dx,y2=y+dy;if(board[`${x},${y}`]||board[`${x2},${y2}`])return false;const points=Object.keys(board).map(k=>k.split(',').map(Number)).concat([[x,y],[x2,y2]]);const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);if(Math.max(...xs)-Math.min(...xs)+1>size||Math.max(...ys)-Math.min(...ys)+1>size)return false;const halves=[{x,y,h:tile.a},{x:x2,y:y2,h:tile.b}],dirs=[[1,0],[-1,0],[0,1],[0,-1]];return halves.some(q=>dirs.some(([ax,ay])=>{const c=board[`${q.x+ax},${q.y+ay}`];return c&&(c.terrain==='castle'||c.terrain===q.h.terrain)}))}
function estimateScore(board){let seen=new Set(),score=0;for(const [k,c] of Object.entries(board)){if(c.terrain==='castle'||seen.has(k))continue;let q=[k],count=0,crowns=0;seen.add(k);while(q.length){const cur=q.pop(),cc=board[cur];count++;crowns+=cc.crowns||0;const [x,y]=cur.split(',').map(Number);for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nk=`${x+dx},${y+dy}`,nc=board[nk];if(nc&&nc.terrain===c.terrain&&!seen.has(nk)){seen.add(nk);q.push(nk)}}}score+=count*crowns}return score}
let cpuBusy=false;function maybeRunCpu(){if(cpuBusy||!isHost()||state?.status!=='playing')return;const tok=state.tokens?.find(t=>t.id===state.activeTokenId),p=tok&&state.players.find(x=>x.id===tok.playerId);if(!p?.cpu)return;cpuBusy=true;setTimeout(()=>{try{if(state.phase==='claim_initial'){let avail=state.currentRow.filter(x=>!x.claimedBy);if(state.settings?.cpuLevel==='easy')avail=[...avail].sort(()=>Math.random()-.5);else avail=[...avail].sort((a,b)=>cpuTileScore(b.tile,p)-cpuTileScore(a.tile,p));if(avail[0])send('claimInitial',{tileNo:avail[0].tile.no,cpuTokenId:tok.id})}else if(state.turnAction==='place'){const cur=state.currentRow.find(x=>x.claimedBy===tok.id);if(cur){const pl=findCpuPlacement(cur.tile,p,state.settings?.cpuLevel||'normal');if(pl)send('place',{...pl,cpuTokenId:tok.id});else send('discard',{cpuTokenId:tok.id})}}else if(state.turnAction==='claim'){let avail=state.nextRow.filter(x=>!x.claimedBy);if(state.settings?.cpuLevel==='easy')avail=[...avail].sort(()=>Math.random()-.5);else avail=[...avail].sort((a,b)=>cpuTileScore(b.tile,p)-cpuTileScore(a.tile,p));if(avail[0])send('claim',{tileNo:avail[0].tile.no,cpuTokenId:tok.id})}}finally{setTimeout(()=>cpuBusy=false,500)}},state.settings?.cpuLevel==='easy'?700:450)}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&currentRoomId&&(!ws||ws.readyState!==WebSocket.OPEN))scheduleReconnect()});window.addEventListener('online',()=>{if(currentRoomId&&(!ws||ws.readyState!==WebSocket.OPEN))scheduleReconnect()});
window.addEventListener('load',()=>{const ar=localStorage.getItem(ACTIVE_ROOM_KEY),an=localStorage.getItem(ACTIVE_NAME_KEY);if(ar&&an){currentRoomId=ar;currentPlayerName=an;token=getToken(ar);connectWs()}else loadRooms()});
